### ISSUE TITLE
$函数设置的有问题哦

### ISSUE THREAD

**Issue by luckyjing** [melodyJie/workAnswer#1]
@melodyJie 
如果我执行`$('       #a')`会怎么样呢？`str[0]`岂不是归到`default`了？仔细想想，如果只使用`querySelectorAll`能不能做到呢？

**Comment by melodyJie** [comment]
现在呢?

**Comment by melodyJie** [comment]
@luckyjing 
现在呢???

**Comment by luckyjing** [comment]
OK
